#should we use IGG for peak calling or not? 
USEIGG: true
#  how is IgG spelled in the filename, eg: "IgG"  for file "G1_IgG_Kasumi_S25_R2.fastq.gz"
IGG: "IgG"
CSIZES:
    - "/home/groups/MaxsonLab/indices/mm10/mm10.chrom.sizes"
GENOME:
    - "/home/groups/MaxsonLab/indices/mm10/mm10"
GENES: 
    - "genes/mm10_refseq_genes.bed"
BOWTIE2:
    HG38:
        - "/home/groups/MaxsonLab/indices/GRch38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index"
    MM10:
        - "/home/groups/MaxsonLab/indices/mm10/mm10"
    ECOLI:
        - "/home/groups/MaxsonLab/indices/ecoli_EB1/genome"
    MYCO:
        - "/home/groups/MaxsonLab/indices/mycoplasma_index/mycoplasma"

FASTA: "/home/groups/MaxsonLab/indices/mm10/mm10.fa"
BANLIST: "/home/groups/MaxsonLab/indices/mm10/mm10.blacklist.v2.bed"